// example of custom API
import groovy.json.JsonSlurperClassic 

@NonCPS
def jsonParse(def json) {
    new groovy.json.JsonSlurperClassic().parseText(json)
}

def repo = "sattarkf/jenkins_learning"

def token = httpRequest authentication: 'github-oauth', contentType: 'APPLICATION_FORM', httpMode: 'POST', requestBody: 'grant_type=client_id', url: 'https://github.com/login/oauth/access_token'
def accessToken = jsonParse(token.content).access_token
def pr = httpRequest customHeaders: [[maskValue: true, name: 'Authorization', value: 'Bearer ' + accessToken]], url: "https://api.github.com/repos/sattarkf/jenkins_learning/pulls"

for (p in jsonParse(pr.content).values) { 
    println(p.source.branch.name)
}
